### ISSUE TITLE
eslint-config is not a convenient rule for determining the allowed length of a string

### ISSUE THREAD

**Issue by SMAY666** [ATS-Lab/eslint-config#1]
```condition: (value: string) => !!value.toLowerCase().match(/^(([^<>()[\]\\.,;:\s@"]+(\.[^<>()[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/)```

Add an exception to the length rule.

**Comment by Kosrotoff** [comment]
Corrected.
